编程的流程逻辑如下所示：

![image.png]()

本章节使用的是数据框的一种变体：tibble。

In [1]:
# 使用的核心R包
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

R语言中的tibble和dataframe都是数据结构，用于存储和处理数据，但它们之间存在一些重要的区别。以下是tibble和dataframe之间的主要区别的表格对比：

| 特征                 | tibble                      | dataframe                  |
|----------------------|-----------------------------|----------------------------|
| 包含包              | 需要加载tidyverse包        | 基本R的一部分             |
| 列名处理            | 自动将非法列名修正为合法   | 不自动修正列名             |
| 数据显示            | 显示较少的数据             | 显示所有的数据             |
| 子集选择            | 不支持 "\$"运算符              | 支持"\$"运算符                |
| 行名处理            | 不允许行名为数字           | 允许行名为数字             |
| 数据框的性质        | 不会将字符向量转换为因子   | 默认将字符向量转换为因子   |
| 输出方式            | 更美观的输出方式           | 基本的文本输出方式         |
| 数据类型推断        | 更智能的数据类型推断       | 基于读入数据时的设置       |
| 列名和行名补全      | 自动补全列名和行名         | 不自动补全列名和行名         |
| 操作符重载          | 支持%>%操作符（管道操作符） | 不支持%>%操作符              |
| 默认的数据类型      | 使用dbl作为数值列的默认类型 | 使用numeric作为数值列的默认类型 |
| 数据切片和过滤      | 使用filter()和slice()函数 | 使用subset()函数和下标操作   |
| 数据添加和修改      | 使用mutate()函数            | 使用$操作符或赋值操作符       |
| 数据排序            | 使用arrange()函数           | 使用order()函数或sort()函数   |
| 缺失值处理          | 使用is.na()和complete()函数 | 使用is.na()和na.omit()函数     |

总的来说，tibble是dataframe的现代化替代品，它在数据处理和显示方面提供了更多的便利性和一致性，尤其是在使用tidyverse包进行数据分析时。然而，如果你需要与旧代码或基本R函数交互，你可能还需要使用dataframe。

其他的R包使用的是标准数据框，因此可以将数据框转换为tibble。

使用到的函数为：as_tibble()函数：

In [2]:
as_tibble(iris)

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1   5.1          3.5         1.4          0.2         setosa
2   4.9          3.0         1.4          0.2         setosa
3   4.7          3.2         1.3          0.2         setosa
4   4.6          3.1         1.5          0.2         setosa
5   5.0          3.6         1.4          0.2         setosa
6   5.4          3.9         1.7          0.4         setosa
7   4.6          3.4         1.4          0.3         setosa
8   5.0          3.4         1.5          0.2         setosa
9   4.4          2.9         1.4          0.2         setosa
10  4.9          3.1         1.5          0.1         setosa
11  5.4          3.7         1.5          0.2         setosa
12  4.8          3.4         1.6          0.2         setosa
13  4.8          3.0         1.4          0.1         setosa
14  4.3          3.0         1.1          0.1         setosa
15  5.8          4.0         1.2          0.2         setosa
16  5.7          4.4         1.5          0.4         setosa
17  5.4          3.9         1.3          0.4         setosa
18  5.1          3.5         1.4          0.3         setosa
19  5.7          3.8         1.7          0.3         setosa
20  5.1          3.8         1.5          0.3         setosa
21  5.4          3.4         1.7          0.2         setosa
22  5.1          3.7         1.5          0.4         setosa
23  4.6          3.6         1.0          0.2         setosa
24  5.1          3.3         1.7          0.5         setosa
25  4.8          3.4         1.9          0.2         setosa
26  5.0          3.0         1.6          0.2         setosa
27  5.0          3.4         1.6          0.4         setosa
28  5.2          3.5         1.5          0.2         setosa
29  5.2          3.4         1.4          0.2         setosa
30  4.7          3.2         1.6          0.2         setosa
⋮   ⋮            ⋮           ⋮            ⋮           ⋮
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

可以通过tibble()函数使用一个向量来创建新tibble，tibble()函数会自动重复长度为1的输入，并且可以使用刚刚创建的新变量：

In [3]:
tibble(
    x = 1:5,
    y = 1,
    z = x ^ 2 + y
)

  x y z
1 1 1  2
2 2 1  5
3 3 1 10
4 4 1 17
5 5 1 26

在tibble中可以使用在R语言中无效的变量名称作为列名称：

In [4]:
# 需要使用反引号
tb <- tibble(
    ':)' = "smile",
    ' ' = "space",
    '2000' = "number"
)

tb

  :)          2000
1 smile space number

如果要在ggplot2和dplyr等其他R包中使用这些变量，也需要使用反引号。

创建tibble的另一种方法是使用tribble()函数，tribble是transposed tibble的缩写。

tribble()函数是定制化的，可以对数据按照行进行编码：列标题由公式（以~开头）定义，数据条目以逗号分隔，这样就可以用易读的方式对少量数据进行布局：

In [5]:
tribble(
    ~x, ~y, ~z,
    #--/--/----
    "a", 2, 3.6,
    "b", 1, 8.5
)

  x y z
1 a 2 3.6
2 b 1 8.5

这里的 #--/--/--- 并不是tribble()语法，只是书写习惯，用来明确指出标题行的位置。

tibble和传统data.frame的使用方法主要有两处不同：打印和取子集。

tibble的打印方法进行了优化，只显示了前10行的结果，并且列也是适合屏幕的，这种方法是适合大数据集的。

In [6]:
tibble(
    a = lubridate::now() + runif(1e3) * 86400,
    b = lubridate::today() + runif(1e3) * 30,
    c = 1:1e3,
    d = runif(1e3),
    e = sample(letters, 1e3, replace = TRUE)
)

     a                   b          c    d           e
1    2024-04-15 11:15:01 2024-04-22  1   0.662983197 k
2    2024-04-14 22:58:09 2024-04-29  2   0.553308865 f
3    2024-04-15 09:03:51 2024-04-28  3   0.185527033 x
4    2024-04-14 23:36:57 2024-04-19  4   0.192641582 d
5    2024-04-15 01:58:43 2024-05-01  5   0.087903857 h
6    2024-04-15 12:13:45 2024-05-05  6   0.795067406 k
7    2024-04-15 03:08:55 2024-05-05  7   0.735231866 c
8    2024-04-15 00:55:39 2024-04-18  8   0.812190503 w
9    2024-04-15 07:36:47 2024-05-09  9   0.645624122 a
10   2024-04-15 09:45:19 2024-05-03 10   0.159989148 c
11   2024-04-15 11:45:31 2024-04-19 11   0.890416415 g
12   2024-04-15 08:31:58 2024-05-13 12   0.561688839 w
13   2024-04-14 15:59:25 2024-05-12 13   0.623567544 y
14   2024-04-15 08:22:10 2024-05-08 14   0.881512990 n
15   2024-04-14 20:36:04 2024-04-21 15   0.412826664 j
16   2024-04-14 16:30:06 2024-04-22 16   0.815694706 a
17   2024-04-14 18:29:45 2024-04-23 17   0.375858851 u
18   2024-04-15 01:23:20 2024-04-18 18   0.283110014 q
19   2024-04-15 02:23:40 2024-05-05 19   0.001148916 a
20   2024-04-15 15:38:52 2024-05-06 20   0.463720359 j
21   2024-04-15 14:39:27 2024-05-06 21   0.740364146 d
22   2024-04-15 03:22:45 2024-05-04 22   0.706695759 o
23   2024-04-15 00:55:18 2024-04-30 23   0.740608718 h
24   2024-04-14 20:31:51 2024-05-04 24   0.521474767 z
25   2024-04-15 10:59:34 2024-05-05 25   0.545227931 g
26   2024-04-14 21:10:42 2024-04-18 26   0.069670698 b
27   2024-04-14 19:56:14 2024-04-18 27   0.908449951 s
28   2024-04-14 19:40:14 2024-04-23 28   0.070532538 c
29   2024-04-15 02:32:03 2024-05-06 29   0.668392394 l
30   2024-04-15 10:15:13 2024-05-06 30   0.234140388 z
⋮    ⋮                   ⋮          ⋮    ⋮           ⋮
971  2024-04-15 10:18:37 2024-05-04  971 0.092286141 z
972  2024-04-14 20:48:58 2024-05-02  972 0.256452949 l
973  2024-04-15 10:04:48 2024-04-16  973 0.853970587 n
974  2024-04-14 20:26:12 2024-04-20  974 0.822413502 q
975  2024-04-15 11:32:49 2024-04-26  975 0.008768177 c
976  2024-04-14 16:22:06 2024-04-30  976 0.827524702 m
977  2024-04-15 11:29:47 2024-04-19  977 0.198629196 h
978  2024-04-14 19:26:16 2024-05-04  978 0.992898462 z
979  2024-04-15 00:21:31 2024-05-13  979 0.194567453 d
980  2024-04-15 08:31:16 2024-05-11  980 0.672181782 l
981  2024-04-15 08:10:16 2024-04-26  981 0.447317684 u
982  2024-04-15 09:53:19 2024-04-20  982 0.226329811 h
983  2024-04-14 22:05:45 2024-04-23  983 0.156801596 e
984  2024-04-15 15:43:55 2024-05-10  984 0.238915077 u
985  2024-04-15 07:43:04 2024-04-27  985 0.233261249 z
986  2024-04-15 06:32:52 2024-05-01  986 0.400428917 w
987  2024-04-15 01:49:06 2024-05-06  987 0.450838639 b
988  2024-04-14 17:51:05 2024-04-22  988 0.691733761 h
989  2024-04-15 03:59:36 2024-05-11  989 0.216864388 v
990  2024-04-14 22:21:00 2024-05-06  990 0.690766012 t
991  2024-04-15 08:39:51 2024-05-08  991 0.755533906 o
992  2024-04-15 14:53:12 2024-05-11  992 0.324599090 n
993  2024-04-15 06:58:24 2024-04-15  993 0.703413303 e
994  2024-04-14 19:41:57 2024-05-04  994 0.957839707 b
995  2024-04-14 23:41:22 2024-05-03  995 0.086769691 a
996  2024-04-15 01:20:03 2024-04-21  996 0.403892591 w
997  2024-04-15 10:32:30 2024-04-22  997 0.946991440 a
998  2024-04-15 00:28:29 2024-05-05  998 0.206448489 y
999  2024-04-14 18:05:40 2024-05-09  999 0.209188282 h
1000 2024-04-15 01:11:24 2024-04-29 1000 0.584653018 h

在打印数据框的时候，tibble的这种设计避免了输出占满整个控制台。

但是有时候需要比默认显示更多的输出，这时候就需要设置几个选项。

In [7]:
# 明确使用print()函数来打印数据框
install.packages("nycflights13")
library(nycflights13)
nycflights13::flights %>%
    print(n = 10, width = Inf)  # 这里使用了管道操作，n = 10意味着打印出来了10行，width = Inf则意味着将所有的列都打印了出来

Installing package into 'C:/Users/wangj/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)

package 'nycflights13' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\wangj\AppData\Local\Temp\RtmpSOzxQ8\downloaded_packages
# A tibble: 336,776 × 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      542            540         2      923            850
 4  2013     1     1      544            545        -1     1004           1022
 5  2013     1     1      554            600        -6      812            837
 6  2013     1     1      554            558        -4      740            728
 7  2013     1     1      555            600        -5      913            854
 8  2013     1     1      557            600        -3      709            723
 9  2013     1     1      557            600        -3      838            846
10  2013     1     1      558            600        -2      753            745
   arr_delay carrier flight tailnum origin dest  air_time distance  hour minute
       <dbl> <chr>    <int> <chr>   <chr>  <chr>    <dbl>    <dbl> <dbl>  <dbl>
 1        11 UA        1545 N14228  EWR    IAH        227     1400     5     15
 2        20 UA        1714 N24211  LGA    IAH        227     1416     5     29
 3        33 AA        1141 N619AA  JFK    MIA        160     1089     5     40
 4       -18 B6         725 N804JB  JFK    BQN        183     1576     5     45
 5       -25 DL         461 N668DN  LGA    ATL        116      762     6      0
 6        12 UA        1696 N39463  EWR    ORD        150      719     5     58
 7        19 B6         507 N516JB  EWR    FLL        158     1065     6      0
 8       -14 EV        5708 N829AS  LGA    IAD         53      229     6      0
 9        -8 B6          79 N593JB  JFK    MCO        140      944     6      0
10         8 AA         301 N3ALAA  LGA    ORD        138      733     6      0
   time_hour
   <dttm>
 1 2013-01-01 05:00:00
 2 2013-01-01 05:00:00
 3 2013-01-01 05:00:00
 4 2013-01-01 05:00:00
 5 2013-01-01 06:00:00
 6 2013-01-01 05:00:00
 7 2013-01-01 06:00:00
 8 2013-01-01 06:00:00
 9 2013-01-01 06:00:00
10 2013-01-01 06:00:00
# ℹ 336,766 more rows

还可以通过设置以下选项来控制默认的打印方式。

• options(tibble.print_max = n, tibble.pring_min = m)：如果多于 m 行，则只打印出 n行。options(tibble.print_min = Inf) 表示总是打印所有行。

• options(tibble.width = Inf) 表示总是打印所有列，不考虑屏幕的宽度。

In [8]:
# 使用R语言的内置数据查看器
nycflights13::flights %>%
  View()

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1     1   517      515             2         830      819
2      2013 1     1   533      529             4         850      830
3      2013 1     1   542      540             2         923      850
4      2013 1     1   544      545            -1        1004     1022
5      2013 1     1   554      600            -6         812      837
6      2013 1     1   554      558            -4         740      728
7      2013 1     1   555      600            -5         913      854
8      2013 1     1   557      600            -3         709      723
9      2013 1     1   557      600            -3         838      846
10     2013 1     1   558      600            -2         753      745
11     2013 1     1   558      600            -2         849      851
12     2013 1     1   558      600            -2         853      856
13     2013 1     1   558      600            -2         924      917
14     2013 1     1   558      600            -2         923      937
15     2013 1     1   559      600            -1         941      910
16     2013 1     1   559      559             0         702      706
17     2013 1     1   559      600            -1         854      902
18     2013 1     1   600      600             0         851      858
19     2013 1     1   600      600             0         837      825
20     2013 1     1   601      600             1         844      850
21     2013 1     1   602      610            -8         812      820
22     2013 1     1   602      605            -3         821      805
23     2013 1     1   606      610            -4         858      910
24     2013 1     1   606      610            -4         837      845
25     2013 1     1   607      607             0         858      915
26     2013 1     1   608      600             8         807      735
27     2013 1     1   611      600            11         945      931
28     2013 1     1   613      610             3         925      921
29     2013 1     1   615      615             0        1039     1100
30     2013 1     1   615      615             0         833      842
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9     30  2123     2125            -2       2223     2247
336748 2013 9     30  2127     2129            -2       2314     2323
336749 2013 9     30  2128     2130            -2       2328     2359
336750 2013 9     30  2129     2059            30       2230     2232
336751 2013 9     30  2131     2140            -9       2225     2255
336752 2013 9     30  2140     2140             0         10       40
336753 2013 9     30  2142     2129            13       2250     2239
336754 2013 9     30  2145     2145             0        115      140
336755 2013 9     30  2147     2137            10         30       27
336756 2013 9     30  2149     2156            -7       2245     2308
336757 2013 9     30  2150     2159            -9       2250     2306
336758 2013 9     30  2159     1845           194       2344     2030
336759 2013 9     30  2203     2205            -2       2339     2331
336760 2013 9     30  2207     2140            27       2257     2250
336761 2013 9     30  2211     2059            72       2339     2242
336762 2013 9     30  2231     2245           -14       2335     2356
336763 2013 9     30  2233     2113            80        112       30
336764 2013 9     30  2235     2001           154         59     2249
336765 2013 9     30  2237     2245            -8       2345     2353
336766 2013 9     30  2240     2245            -5       2334     2351
336767 2013 9     30  2240     2250           -10       2347        7
336768 2013 9     30  2241     2246            -5       2345        1
336769 2013 9     30  2307     2255            12       2359     2358
336770 2013 9     30  2349     2359           -10        325      350
336771 2013 9     30    NA     1842            NA         NA     2019
336772 2013 9     30    NA     1455            NA         NA     1634
336773 2013 9     30    NA     2200            NA         NA     2312
336774 2013 9     30    NA     1210            NA         NA     1330
336775 2013 9     30    NA     1159            NA         NA     1344
336776 2013 9     30    NA      840            NA         NA     1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
1       11       UA      1545   N14228  EWR    IAH  227      1400     5
2       20       UA      1714   N24211  LGA    IAH  227      1416     5
3       33       AA      1141   N619AA  JFK    MIA  160      1089     5
4      -18       B6       725   N804JB  JFK    BQN  183      1576     5
5      -25       DL       461   N668DN  LGA    ATL  116       762     6
6       12       UA      1696   N39463  EWR    ORD  150       719     5
7       19       B6       507   N516JB  EWR    FLL  158      1065     6
8      -14       EV      5708   N829AS  LGA    IAD   53       229     6
9       -8       B6        79   N593JB  JFK    MCO  140       944     6
10       8       AA       301   N3ALAA  LGA    ORD  138       733     6
11      -2       B6        49   N793JB  JFK    PBI  149      1028     6
12      -3       B6        71   N657JB  JFK    TPA  158      1005     6
13       7       UA       194   N29129  JFK    LAX  345      2475     6
14     -14       UA      1124   N53441  EWR    SFO  361      2565     6
15      31       AA       707   N3DUAA  LGA    DFW  257      1389     6
16      -4       B6      1806   N708JB  JFK    BOS   44       187     5
17      -8       UA      1187   N76515  EWR    LAS  337      2227     6
18      -7       B6       371   N595JB  LGA    FLL  152      1076     6
19      12       MQ      4650   N542MQ  LGA    ATL  134       762     6
20      -6       B6       343   N644JB  EWR    PBI  147      1023     6
21      -8       DL      1919   N971DL  LGA    MSP  170      1020     6
22      16       MQ      4401   N730MQ  LGA    DTW  105       502     6
23     -12       AA      1895   N633AA  EWR    MIA  152      1085     6
24      -8       DL      1743   N3739P  JFK    ATL  128       760     6
25     -17       UA      1077   N53442  EWR    MIA  157      1085     6
26      32       MQ      3768   N9EAMQ  EWR    ORD  139       719     6
27      14       UA       303   N532UA  JFK    SFO  366      2586     6
28       4       B6       135   N635JB  JFK    RSW  175      1074     6
29     -21       B6       709   N794JB  JFK    SJU  182      1598     6
30      -9       DL       575   N326NB  EWR    ATL  120       746     6
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 -24       EV      5489   N712EV  LGA    CHO   45       305     21
336748  -9       EV      3833   N16546  EWR    CLT   72       529     21
336749 -31       B6        97   N807JB  JFK    DEN  213      1626     21
336750  -2       EV      5048   N751EV  LGA    RIC   45       292     20
336751 -30       MQ      3621   N807MQ  JFK    DCA   36       213     21
336752 -30       AA       185   N335AA  JFK    LAX  298      2475     21
336753  11       EV      4509   N12957  EWR    PWM   47       284     21
336754 -25       B6      1103   N633JB  JFK    SJU  192      1598     21
336755   3       B6      1371   N627JB  LGA    FLL  139      1076     21
336756 -23       UA       523   N813UA  EWR    BOS   37       200     21
336757 -16       EV      3842   N10575  EWR    MHT   39       209     21
336758 194       9E      3320   N906XJ  JFK    BUF   50       301     18
336759   8       EV      5311   N722EV  LGA    BGR   61       378     22
336760   7       MQ      3660   N532MQ  LGA    BNA   97       764     21
336761  57       EV      4672   N12145  EWR    STL  120       872     20
336762 -21       B6       108   N193JB  JFK    PWM   48       273     22
336763  42       UA       471   N578UA  EWR    SFO  318      2565     21
336764 130       B6      1083   N804JB  JFK    MCO  123       944     20
336765  -8       B6       234   N318JB  JFK    BTV   43       266     22
336766 -17       B6      1816   N354JB  JFK    SYR   41       209     22
336767 -20       B6      2002   N281JB  JFK    BUF   52       301     22
336768 -16       B6       486   N346JB  JFK    ROC   47       264     22
336769   1       B6       718   N565JB  JFK    BOS   33       187     22
336770 -25       B6       745   N516JB  JFK    PSE  196      1617     23
336771  NA       EV      5274   N740EV  LGA    BNA   NA       764     18
336772  NA       9E      3393   NA      JFK    DCA   NA       213     14
336773  NA       9E      3525   NA      LGA    SYR   NA       198     22
336774  NA       MQ      3461   N535MQ  LGA    BNA   NA       764     12
336775  NA       MQ      3572   N511MQ  LGA    CLE   NA       419     11
336776  NA       MQ      3531   N839MQ  LGA    RDU   NA       431      8
       minute time_hour
1      15     2013-01-01 05:00:00
2      29     2013-01-01 05:00:00
3      40     2013-01-01 05:00:00
4      45     2013-01-01 05:00:00
5       0     2013-01-01 06:00:00
6      58     2013-01-01 05:00:00
7       0     2013-01-01 06:00:00
8       0     2013-01-01 06:00:00
9       0     2013-01-01 06:00:00
10      0     2013-01-01 06:00:00
11      0     2013-01-01 06:00:00
12      0     2013-01-01 06:00:00
13      0     2013-01-01 06:00:00
14      0     2013-01-01 06:00:00
15      0     2013-01-01 06:00:00
16     59     2013-01-01 05:00:00
17      0     2013-01-01 06:00:00
18      0     2013-01-01 06:00:00
19      0     2013-01-01 06:00:00
20      0     2013-01-01 06:00:00
21     10     2013-01-01 06:00:00
22      5     2013-01-01 06:00:00
23     10     2013-01-01 06:00:00
24     10     2013-01-01 06:00:00
25      7     2013-01-01 06:00:00
26      0     2013-01-01 06:00:00
27      0     2013-01-01 06:00:00
28     10     2013-01-01 06:00:00
29     15     2013-01-01 06:00:00
30     15     2013-01-01 06:00:00
⋮      ⋮      ⋮
336747 25     2013-09-30 21:00:00
336748 29     2013-09-30 21:00:00
336749 30     2013-09-30 21:00:00
336750 59     2013-09-30 20:00:00
336751 40     2013-09-30 21:00:00
336752 40     2013-09-30 21:00:00
336753 29     2013-09-30 21:00:00
336754 45     2013-09-30 21:00:00
336755 37     2013-09-30 21:00:00
336756 56     2013-09-30 21:00:00
336757 59     2013-09-30 21:00:00
336758 45     2013-09-30 18:00:00
336759  5     2013-09-30 22:00:00
336760 40     2013-09-30 21:00:00
336761 59     2013-09-30 20:00:00
336762 45     2013-09-30 22:00:00
336763 13     2013-09-30 21:00:00
336764  1     2013-09-30 20:00:00
336765 45     2013-09-30 22:00:00
336766 45     2013-09-30 22:00:00
336767 50     2013-09-30 22:00:00
336768 46     2013-09-30 22:00:00
336769 55     2013-09-30 22:00:00
336770 59     2013-09-30 23:00:00
336771 42     2013-09-30 18:00:00
336772 55     2013-09-30 14:00:00
336773  0     2013-09-30 22:00:00
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

如果想要提取单个变量，那么就需要一些新工具，如 $  和 [[ 。

[[ 可以按照名称或者位置来提取变量；$只能够按名称提取变量，单可以减少一些输入：

In [9]:
df <- tibble(
    x = runif(5),
    y = runif(5)
)

In [10]:
df

  x         y
1 0.1907492 0.1115748
2 0.4382729 0.5777855
3 0.7526293 0.3340556
4 0.4060962 0.9327560
5 0.9251995 0.3948725

In [11]:
# 按名称提取
df$x

[1] 0.1907492 0.4382729 0.7526293 0.4060962 0.9251995

In [12]:
# 按位置提取
df[[1]]

[1] 0.1907492 0.4382729 0.7526293 0.4060962 0.9251995

In [13]:
# 使用管道进行操作，需要使用特殊占位符 .
df %>% .$x

[1] 0.1907492 0.4382729 0.7526293 0.4060962 0.9251995

与data.frame相比，tibble更加的严格：它不能够进行部分匹配，如果想要访问的列不存在，它会生成一条警告信息。

**练习**

In [14]:
# 如何识别一个对象是否为 tibble
class(mtcars)

[1] "data.frame"

In [15]:
is_tibble(mtcars)

[1] FALSE

In [16]:
class(as_tibble(mtcars))

[1] "tbl_df"     "tbl"        "data.frame"

In [17]:
is_tibble(as_tibble(mtcars))

[1] TRUE

In [18]:
# 对比在 data.frame 和等价的 tibble 上进行的以下操作。
df <- data.frame(abc = 1, xyz = "a")
df$x
df[, "xyz"]
df[,c("abc", "xyz")]

[1] "a"

[1] "a"

  abc xyz
1 1   a

In [19]:
df <- as_tibble(df)
df$x
df[, "xyz"]
df[,c("abc", "xyz")]

Warning message:
"Unknown or uninitialised column: `x`."

NULL

  xyz
1 a

  abc xyz
1 1   a

$ 运算符将匹配以其后的名称开头的任何列名称。 由于存在名为 xyz 的列，因此表达式 df\$x 将扩展为 df\$xyz。 \$ 运算符的这种行为可以节省一些击键次数，但可能会导致意外使用与您想象的不同的列。

对于 data.frames，对于 [，返回的对象类型因列数而异。 如果是一列，则不会返回 data.frame，而是返回一个向量。 如果有多个列，那么它将返回一个 data.frame。 如果您知道要传递的内容，这很好，但假设您执行了 df[ , vars] ，其中 vars 是变量。 那么该代码的作用取决于长度（变量），并且您必须编写代码来解决这些情况或风险错误。

In [20]:
# 如果将一个变量的名称保存在一个对象中，如 var <- "mpg"，如何从 tibble 中提取出这个变量？

# 创建一个示例tibble
my_tibble <- tibble(mpg = c(20, 30, 25), cyl = c(4, 6, 4))

# 将变量名称保存在一个对象中
var <- "mpg"

# 使用$运算符和反引号提取变量
variable <- my_tibble$`var`

# 打印提取的变量
print(variable)

Warning message:
"Unknown or uninitialised column: `var`."

NULL

In [21]:
# What does tibble::enframe() do? When might you use it?
enframe(c(a = 1, b = 2, c = 3))

  name value
1 a    1
2 b    2
3 c    3

In [22]:
# 哪个选项控制在 tibble 底部打印的额外列名称的数量？
?print.tbl

formatting               package:tibble                R Documentation

_P_r_i_n_t_i_n_g _t_i_b_b_l_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     One of the main features of the 'tbl_df' class is the printing:

        * Tibbles only print as many rows and columns as fit on one
          screen, supplemented by a summary of the remaining rows and
          columns.

        * Tibble reveals the type of each column, which keeps the user
          informed about whether a variable is, e.g., <chr> or <fct>
          (character versus factor). See 'vignette("types")' for an
          overview of common type abbreviations.

     Printing can be tweaked for a one-off call by calling 'print()'
     explicitly and setting arguments like 'n' and 'width'. More
     persistent control is available by setting the options described
     in pillar::pillar_options. See also 'vignette("digits")' for a
     comparison to base options, and 'vignette("numbers")' that
     showcases 'num()' and 'char()' for creating columns with custom
     formatting options.

     As of tibble 3.1.0, printing is handled entirely by the 'pillar'
     package. If you implement a package that extends tibble, the
     printed output can be customized in various ways. See
     'vignette("extending", package = "pillar")' for details, and
     pillar::pillar_options for options that control the display in the
     console.

_U_s_a_g_e:

     ## S3 method for class 'tbl_df'
     print(
       x,
       width = NULL,
       ...,
       n = NULL,
       max_extra_cols = NULL,
       max_footer_lines = NULL
     )

     ## S3 method for class 'tbl_df'
     format(
       x,
       width = NULL,
       ...,
       n = NULL,
       max_extra_cols = NULL,
       max_footer_lines = NULL
     )

_A_r_g_u_m_e_n_t_s:

       x: Object to format or print.

   width: Width of text output to generate. This defaults to 'NULL',
          which means use the 'width' option.

     ...: Passed on to 'tbl_format_setup()'.

       n: Number of rows to show. If 'NULL', the default, will print
          all rows if less than the 'print_max' option. Otherwise, will
          print as many rows as specified by the 'print_min' option.

max_extra_cols: Number of extra columns to print abbreviated
          information for, if the width is too small for the entire
          tibble. If 'NULL', the 'max_extra_cols' option is used. The
          previously defined 'n_extra' argument is soft-deprecated.

max_footer_lines: Maximum number of footer lines. If 'NULL', the
          'max_footer_lines' option is used.

_E_x_a_m_p_l_e_s:

     print(as_tibble(mtcars))
     print(as_tibble(mtcars), n = 1)
     print(as_tibble(mtcars), n = 3)

     print(as_tibble(trees), n = 100)

     print(mtcars, width = 10)

     mtcars2 <- as_tibble(cbind(mtcars, mtcars), .name_repair = "unique")
     print(mtcars2, n = 25, max_extra_cols = 3)


     print(nycflights13::flights, max_footer_lines = 1)
     print(nycflights13::flights, width = Inf)